### ISSUE TITLE
能否将xray修改为vless+443端口

### ISSUE THREAD

**Issue by crosspacific** [wy580477/Leech-AIO-APP-EX#44]
现有的的vmess协议，能修改为vless吗？我自己试了一下改协议，改端口不成功。xray日志里出现错误。如不能改变，可否提供一些思路我自己修改呢？谢谢。

**Comment by wy580477** [comment]
```
- port: 61807
  protocol: vmess
  settings:
    clients:
    - id: VmessUUID
    decryption: none
  streamSettings:
    network: ws
    wsSettings:
      path: GLOBAL_PORTAL_PATH/vm
```
